// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: porker/resource.proto

package porker

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Violations int32

const (
	Violations_UNDEFINED_VIOLATION Violations = 0
)

// Enum value maps for Violations.
var (
	Violations_name = map[int32]string{
		0: "UNDEFINED_VIOLATION",
	}
	Violations_value = map[string]int32{
		"UNDEFINED_VIOLATION": 0,
	}
)

func (x Violations) Enum() *Violations {
	p := new(Violations)
	*p = x
	return p
}

func (x Violations) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Violations) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_resource_proto_enumTypes[0].Descriptor()
}

func (Violations) Type() protoreflect.EnumType {
	return &file_porker_resource_proto_enumTypes[0]
}

func (x Violations) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Violations.Descriptor instead.
func (Violations) EnumDescriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{0}
}

type RoomState int32

const (
	RoomState_ROOM_STATE_UNKNOWN   RoomState = 0
	RoomState_ROOM_STATE_TURN_DOWN RoomState = 1
	RoomState_ROOM_STATE_OPEN      RoomState = 2
)

// Enum value maps for RoomState.
var (
	RoomState_name = map[int32]string{
		0: "ROOM_STATE_UNKNOWN",
		1: "ROOM_STATE_TURN_DOWN",
		2: "ROOM_STATE_OPEN",
	}
	RoomState_value = map[string]int32{
		"ROOM_STATE_UNKNOWN":   0,
		"ROOM_STATE_TURN_DOWN": 1,
		"ROOM_STATE_OPEN":      2,
	}
)

func (x RoomState) Enum() *RoomState {
	p := new(RoomState)
	*p = x
	return p
}

func (x RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_resource_proto_enumTypes[1].Descriptor()
}

func (RoomState) Type() protoreflect.EnumType {
	return &file_porker_resource_proto_enumTypes[1]
}

func (x RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState.Descriptor instead.
func (RoomState) EnumDescriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{1}
}

type Point int32

const (
	Point_POINT_UNKNOWN  Point = 0
	Point_POINT_0        Point = 1
	Point_POINT_HALF     Point = 2
	Point_POINT_1        Point = 3
	Point_POINT_2        Point = 4
	Point_POINT_3        Point = 5
	Point_POINT_5        Point = 6
	Point_POINT_8        Point = 7
	Point_POINT_13       Point = 8
	Point_POINT_21       Point = 9
	Point_POINT_COFFEE   Point = 20
	Point_POINT_QUESTION Point = 21
	Point_NOT_VOTE       Point = 99
)

// Enum value maps for Point.
var (
	Point_name = map[int32]string{
		0:  "POINT_UNKNOWN",
		1:  "POINT_0",
		2:  "POINT_HALF",
		3:  "POINT_1",
		4:  "POINT_2",
		5:  "POINT_3",
		6:  "POINT_5",
		7:  "POINT_8",
		8:  "POINT_13",
		9:  "POINT_21",
		20: "POINT_COFFEE",
		21: "POINT_QUESTION",
		99: "NOT_VOTE",
	}
	Point_value = map[string]int32{
		"POINT_UNKNOWN":  0,
		"POINT_0":        1,
		"POINT_HALF":     2,
		"POINT_1":        3,
		"POINT_2":        4,
		"POINT_3":        5,
		"POINT_5":        6,
		"POINT_8":        7,
		"POINT_13":       8,
		"POINT_21":       9,
		"POINT_COFFEE":   20,
		"POINT_QUESTION": 21,
		"NOT_VOTE":       99,
	}
)

func (x Point) Enum() *Point {
	p := new(Point)
	*p = x
	return p
}

func (x Point) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Point) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_resource_proto_enumTypes[2].Descriptor()
}

func (Point) Type() protoreflect.EnumType {
	return &file_porker_resource_proto_enumTypes[2]
}

func (x Point) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Point.Descriptor instead.
func (Point) EnumDescriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{2}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId   string `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porker_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_porker_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Login) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *Login) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Ballot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId string `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	Point   Point  `protobuf:"varint,2,opt,name=point,proto3,enum=porker.Point" json:"point,omitempty"`
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porker_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_porker_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Ballot) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *Ballot) GetPoint() Point {
	if x != nil {
		return x.Point
	}
	return Point_POINT_UNKNOWN
}

type PokerSituation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId        string    `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MasterLoginId string    `protobuf:"bytes,2,opt,name=master_login_id,json=masterLoginId,proto3" json:"master_login_id,omitempty"`
	State         RoomState `protobuf:"varint,3,opt,name=state,proto3,enum=porker.RoomState" json:"state,omitempty"`
	Ballot        []*Ballot `protobuf:"bytes,4,rep,name=ballot,proto3" json:"ballot,omitempty"`
}

func (x *PokerSituation) Reset() {
	*x = PokerSituation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porker_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokerSituation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokerSituation) ProtoMessage() {}

func (x *PokerSituation) ProtoReflect() protoreflect.Message {
	mi := &file_porker_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokerSituation.ProtoReflect.Descriptor instead.
func (*PokerSituation) Descriptor() ([]byte, []int) {
	return file_porker_resource_proto_rawDescGZIP(), []int{2}
}

func (x *PokerSituation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PokerSituation) GetMasterLoginId() string {
	if x != nil {
		return x.MasterLoginId
	}
	return ""
}

func (x *PokerSituation) GetState() RoomState {
	if x != nil {
		return x.State
	}
	return RoomState_ROOM_STATE_UNKNOWN
}

func (x *PokerSituation) GetBallot() []*Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

var File_porker_resource_proto protoreflect.FileDescriptor

var file_porker_resource_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x22,
	0x41, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x48, 0x0a, 0x06, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0xa2, 0x01, 0x0a,
	0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x74, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x70, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x61, 0x6c,
	0x6c, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x52, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f,
	0x74, 0x2a, 0x25, 0x0a, 0x0a, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x17, 0x0a, 0x13, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x56, 0x49, 0x4f,
	0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x2a, 0x52, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x55, 0x52, 0x4e,
	0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x02, 0x2a, 0xc8, 0x01, 0x0a,
	0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x49,
	0x4e, 0x54, 0x5f, 0x30, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x48, 0x41, 0x4c, 0x46, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x31, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x32, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x33, 0x10, 0x05, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x35, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f,
	0x49, 0x4e, 0x54, 0x5f, 0x38, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x49, 0x4e, 0x54,
	0x5f, 0x31, 0x33, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x32,
	0x31, 0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x46,
	0x46, 0x45, 0x45, 0x10, 0x14, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x15, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54,
	0x5f, 0x56, 0x4f, 0x54, 0x45, 0x10, 0x63, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x3b, 0x70, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_porker_resource_proto_rawDescOnce sync.Once
	file_porker_resource_proto_rawDescData = file_porker_resource_proto_rawDesc
)

func file_porker_resource_proto_rawDescGZIP() []byte {
	file_porker_resource_proto_rawDescOnce.Do(func() {
		file_porker_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_porker_resource_proto_rawDescData)
	})
	return file_porker_resource_proto_rawDescData
}

var file_porker_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_porker_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_porker_resource_proto_goTypes = []interface{}{
	(Violations)(0),        // 0: porker.Violations
	(RoomState)(0),         // 1: porker.RoomState
	(Point)(0),             // 2: porker.Point
	(*Login)(nil),          // 3: porker.Login
	(*Ballot)(nil),         // 4: porker.Ballot
	(*PokerSituation)(nil), // 5: porker.PokerSituation
}
var file_porker_resource_proto_depIdxs = []int32{
	2, // 0: porker.Ballot.point:type_name -> porker.Point
	1, // 1: porker.PokerSituation.state:type_name -> porker.RoomState
	4, // 2: porker.PokerSituation.ballot:type_name -> porker.Ballot
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_porker_resource_proto_init() }
func file_porker_resource_proto_init() {
	if File_porker_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_porker_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porker_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ballot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porker_resource_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokerSituation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_porker_resource_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_porker_resource_proto_goTypes,
		DependencyIndexes: file_porker_resource_proto_depIdxs,
		EnumInfos:         file_porker_resource_proto_enumTypes,
		MessageInfos:      file_porker_resource_proto_msgTypes,
	}.Build()
	File_porker_resource_proto = out.File
	file_porker_resource_proto_rawDesc = nil
	file_porker_resource_proto_goTypes = nil
	file_porker_resource_proto_depIdxs = nil
}
